#!/usr/bin/sh

# Defining color scheme
#

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color]]'

# Utils functions
#
function display_result_string {
    rc=$1

    if [[ "$rc" == 0 ]]; then
        echo -e "${GREEN}Success${NC}"
    else
        echo -e "${RED}Failure${NC}"
    fi
}

# Bulk of the code
#
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

echo "Starting commit sanity checking ..."
echo ""

echo -n "[tox] Ensuring tox passes... "
tox_test_out=$(tox)
tox_rc=$?
display_result_string $tox_rc
if [[ "${tox_rc}" != 0 ]]; then
    echo ""
    echo "${tox_test_out}"
    echo ""
fi


echo -n "[whitespace] Ensure no whitespace are present... "
ws_test_out=$(git diff-index --check --cached $against -- 2>&1)
ws_rc=$?
display_result_string $ws_rc
if [[ "${ws_rc}" != 0 ]]; then
    echo ""
    echo "${ws_test_out}"
    echo ""
fi
echo ""

if [[ "${tox_rc}" != 0 ]] || [[ "${ws_rc}" != 0 ]]; then
    echo ""
    echo -e "${RED}Your commit hasn't passed the sanity check pre-commit hook. Please fix the aforementionned issue and ammend your commit${NC}"
    exit 1
fi
